<tr>
    <td class="label">
        <label>
            <span><?php echo __('Installation guide')?></span>
        </label>
    </td>
    <td class="value paypal-installation-guide">
        <h4 class="title"><?php echo __('Install the Paypal REST SDK')?></h4>
        <ul class="paypal-installation-skd-guide">
            <li>
                <?php echo __('If you can access to your server via SSH:');?><br />
                <div class="guide-content">
                    <?php echo __('Use cd command to your Magento root folder. After that, enter the command:');?>
                    <br />
                    <b>composer require "paypal/rest-api-sdk-php:*"</b>
                    <br />
                    <a href="https://developer.paypal.com/docs/api/quickstart/install/"><?php echo __('View detail')?></a>
                </div>
            </li>
            <li>
                <?php echo __('You can also download the SDK manually:');?><br />
                <ol class="guide-content">
                    <li>
                        <?php echo __('Download latest/desired release zip file starting with PayPal-PHP-SDK-*.zip from ')?>
                        <a href="https://github.com/paypal/PayPal-PHP-SDK/releases"><?php echo __("Releases Section")?></a>
                    </li>
                    <li><?php echo __('Unzip and copy the folder named "paypal" to "vendor" folder on your Magento root folder');?></li>
                    <li><?php echo __('The directory structure would look like: Your Magento root folder > vendor > paypal');?></li>
                </ol>
            </li>
        </ul>
        <h4 class="title"><?php echo __('Get your application infomation')?></h4>
        <ul class="paypal-installation-app-guide">
            <li>
                <ol class="guide-content">
                    <li>
                        <?php echo __('Login to your account at')?>
                        <a href="https://developer.paypal.com/"><?php echo __("Paypal Developer")?></a>
                    </li>
                    <li>
                        <?php echo __('Go to ');?>
                        <a href="https://developer.paypal.com/developer/applications/"><?php echo __("Dashboard")?></a>
                    </li>
                    <li><?php echo __('Click button "Create App" to create a new one if you want');?></li>
                    <li><?php echo __('On the list Apps, click on the name of the App to view detail');?></li>
                    <li><?php echo __('Now you can find the API credentials as Account, Client Id, Secret');?></li>
                    <li><?php echo __('Copy the required information and fill into the above configurations');?></li>
                </ol>
            </li>
        </ul>
        <h4 class="title"><?php echo __('Test the API connection')?></h4>
        <ul class="paypal-installation-test">
            <li><?php echo __('After install the SDK and save all the API information, you can click the button below to test the connection');?></li>
            <li><button type="button" id="webpos-paypal-integration-test-api"><?php echo __('Test API connection');?></button></li>
            <li>
                <div id="webpos-paypal-integration-test-response">
                    <div class="loader hide"></div>
                    <div class="success hide"><?php echo __('Success');?></div>
                    <div class="error hide"><?php echo __('Error');?></div>
                </div>
            </li>
        </ul>
    </td>
    <td class=""></td>
</tr>
<script>
    require([
        'jquery'
    ], function ($) {
        var testAPIUrl = '<?php echo $block->getTestApiUrl();?>';
        $(document).ready(function(){
            $('#webpos-paypal-integration-test-api').click(function(){
                $("#webpos-paypal-integration-test-response .loader").removeClass('hide');
                $.ajax({
                    method:'get',
                    url: testAPIUrl
                }).complete(function( result, status) {
                    $("#webpos-paypal-integration-test-response .loader").addClass('hide');
                    if(status == 'success'){
                        var response = JSON.parse(result.responseText);
                        if(response && response.success){
                            $("#webpos-paypal-integration-test-response .success").removeClass('hide');
                            $("#webpos-paypal-integration-test-response .error").addClass('hide');
                        }else{
                            if(response && response.message){
                                alert(response.message);
                            }
                            $("#webpos-paypal-integration-test-response .success").addClass('hide');
                            $("#webpos-paypal-integration-test-response .error").removeClass('hide');
                        }
                    }else{
                        alert('<?php echo __('Please check your network connection');?>');
                    }
                });
            });
        });
    });
</script>
<style type="text/css">
    .hide{
        display: none;
    }
    .paypal-installation-guide h4.title{
        padding-top:7px;
        padding-left:0px;
        margin-top:0px;
        margin-left:0px;
        font-size: 14px;
        font-weight: 600;
    }
    .paypal-installation-guide ul li{
        list-style: none;
        margin: 5px 0px;
    }
    .paypal-installation-guide ol li{
        list-style: inherit;
    }
    .paypal-installation-guide li .guide-content{
        padding-left: 20px;
    }
    .loader {
        border: 6px solid #f3f3f3; /* Light grey */
        border-top: 6px solid #3498db; /* Blue */
        border-radius: 50%;
        width: 40px;
        height: 40px;
        animation: spin 1.5s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>