<!-- Modal -->
<div class="modal right fade" id="import_product" tabindex="-1" role="dialog" aria-labelledby="modalLabel" style="display:none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <h2 class="modal-title" data-role="title"><?php echo $this->__($this->getTitle())?></h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <div class="modal-header">
                <button id="submit-import" class="action-primary import-csv" type="button" data-role="action">
                    <span><span><?php echo $this->__('Import')?></span></span>
                </button>
            </div>

            <div class="modal-body">
                <div class="os_panel">
                    <div class="header">
                        <label><?php echo $this->__('Instruction');?></label>
                    </div>
                    <ul class="content">
                        <li class="item">
                            <span><?php echo $this->__($this->getContent());?></span>
                            <span data-role="data" data-key="form" data-type="text" class="value"></span>
                            <div class="clear"></div>
                        </li>
                        <li class="item">
                            <span><a href="<?php echo $this->getCsvSampleLink();?>"><?php echo $this->__('Download'); ?></a></span>
                        </li>
                    </ul>
                </div>
                <div class="import-product">
                    <?php //if ($this->getUseContainer()): ?>
                    <?php if (1==1): ?>
                    <form id="import-product-form" class="admin__fieldset" action="<?php /* @escapeNotVerified */ echo $this->getImportLink() ?>" method="post" enctype="multipart/form-data">
                        <?php endif; ?>
                        <?php echo $this->getBlockHtml('formkey')?>
                        <div class="fieldset admin__field">
                            <label for="import_product" class="admin__field-label"><span><?php /* @escapeNotVerified */ echo $this->__('Please choose  a CSV file to import:') ?></span></label>
                            <div class="admin__field-control">
                                <input type="file" id="import_product_file" name="import_product" class="input-file required-entry"/>
                            </div>
                        </div>
                        <?php if (1==1):  ?>
                    </form>
                <?php endif; ?>
                </div>
            </div>
        </div><!-- modal-content -->
    </div><!-- modal-dialog -->
</div><!-- modal -->

<script type="text/javascript">
    jQuery('#submit-import').click(function() {
        var form = new varienForm('import-product-form');
        if(form.validate()) {
            form.submit();
        }        
    });
</script>