<?php
/**
 * Copyright © 2018 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div id="webpos_bambora_integration" data-bind="scope:'webpos-bambora-integration'">
    <script type="text/x-magento-init">
        {
            "#webpos_bambora_integration": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout(); ?>
            }
        }
    </script>
</div>

