<!-- Modal -->
<div class="modal right fade" id="import-request-receiving" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <h2 class="modal-title" data-role="title"><?php echo $this->__($this->getTitle()) ?></h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <div class="modal-header">
                <button id="submit-import-receiving" class="action-primary import_button" type="button"
                        data-role="action">
                    <span><?php echo $this->__('Import') ?></span>
                </button>
            </div>

            <div class="modal-body">
                <div class="os_panel">
                    <div class="header">
                        <label><?php echo $this->__('Instruction'); ?></label>
                    </div>
                    <ul class="content">
                        <li class="item">
                            <span><?php echo $this->__($this->getContent()); ?></span>
                            <span data-role="data" data-key="form" data-type="text" class="value"></span>
                            <div class="clear"></div>
                        </li>
                        <li class="item">
                            <span><?php echo $this->__("Import products by SKU:") ?> <a
                                    href="<?php echo $this->getCsvSampleLink(); ?>"><?php echo $this->__('Download'); ?></a></span>
                            <br>
                            <?php if(Magestore_Inventorysuccess_Helper_Data::isBarcodeInstalled()): ?>
                                <span><?php echo $this->__("Import products by Barcode:") ?> <a
                                        href="<?php echo $this->getCsvBarcodeSampleLink(); ?>"><?php echo $this->__('Download'); ?></a></span>
                            <?php endif; ?>
                        </li>
                    </ul>
                </div>
                <div class="import-product">
                    <form id="import-request-receiving-form" class="admin__fieldset"
                          action="<?php /* @escapeNotVerified */
                          echo $this->getImportLink() ?>" method="post" enctype="multipart/form-data">
                        <?php echo $this->getBlockHtml('formkey') ?>
                        <div class="fieldset admin__field">
                            <label for="import_product" class="admin__field-label"><span><?php /* @escapeNotVerified */
                                    echo $this->__('Please choose  a CSV file to import:') ?></span></label>
                            <div class="admin__field-control">
                                <input accept=".csv" type="file" id="import-request-receiving-file"
                                       name="import-request-receiving"
                                       class="input-file required-entry"/>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- modal-content -->
    </div><!-- modal-dialog -->
</div><!-- modal -->

<script type="text/javascript">
    jQuery('#submit-import-receiving').click(function () {
        if (jQuery('#import-request-receiving-file')[0].files.length)
            jQuery('#import-request-receiving-form').submit();
    });
</script>