<?php
/**
 * Copyright © 2018 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Transparent\Iframe $block
 */
$params = $block->getParams();

?>
<html>
<head>
    <script>
        <?php if (isset($params['redirect'])): ?>
        window.location="<?php echo $block->escapeUrl($params['redirect']); ?>";
        <?php else: ?>
        var parentWindow = window.opener;
        if(parentWindow && parentWindow.payflowproModel){
            <?php if ((isset($params['success']) && $params['success'] == 1) || isset($params['order_success'])): ?>
            parentWindow.payflowproModel.success();
            <?php endif; ?>
            <?php if (isset($params['error_msg'])): ?>
            parentWindow.payflowproModel.error("<?php echo addslashes($params['error_msg']);?>");
            <?php endif; ?>
            window.close();
        }
        <?php endif; ?>
    </script>
</head>
<body>
</body>
</html>
