<div class="steps-wizard">
    <div class="steps-wizard-navigation">
        <ul class="nav-timeline-bar">
            <?php foreach ($this->getSteps() as $step):?>
            <li <?php if($this->isActive($step)){echo 'class="active"';}?>>
                <a href="<?php echo $step['url']?>" >
                    <?php echo$step['title']?>
                </a>
            </li>
            <?php endforeach;?>
        </ul>
    </div>
</div>
<style type="text/css">
    .steps-wizard {
        float: left;
        position: relative;
        box-sizing: inherit;
        display: block;
        overflow: auto;
    }

    .steps-wizard-navigation{
        border-bottom: none;
        border-top: none;
        margin: 0;
        padding: 0;
        text-align: left;
        background: #f8f8f8;
    }

    .nav-timeline-bar {
        counter-reset: i;
        float: left;
        padding: 0;
        position: relative;
        white-space: nowrap;
        text-align: left;
    }
    .nav-timeline-bar:before{
        background-color: #d4d4d4;
        border-bottom: 1px solid #d9d9d9;
        border-top: 1px solid #bfbfbf;
        content: '';
        height: 9px;
        left: 38px;
        position: absolute;
        right: 50px;
        top: 11px;
    }

    .nav-timeline-bar li{
        display: inline-block;
        font-size: 0;
        position: relative;
        vertical-align: top;
        width: 70px;
    }

    .nav-timeline-bar > li:after{
        background-color: #514943;
        content: '';
        height: 5px;
        left: -40px;
        position: absolute;
        top: 13px;
        width: 91%;
        box-sizing: inherit;
        right: 50px;
    }

    .nav-timeline-bar > li:first-child:after{
        display: none;
    }

    .nav-timeline-bar > li.active ~ li:after{
        display: none;
    }

    .nav-timeline-bar > li.active a{
        color: #000000;
        content: '';
    }

    .nav-timeline-bar > li.active a:after{
        background-color: #ffffff !important;
        content: '';
    }

    .nav-timeline-bar a {
        text-overflow: initial;
        white-space: normal;
        color: #000000;
        display: block;
        font-size: 12px;
        font-weight: 700;
        line-height: 1.2;
        overflow: hidden;
        padding: 27px 0px 0;
        position: relative;
        text-align: center;
        text-decoration: none;
    }

    .nav-timeline-bar > li.active ~ li a:after{
        background-color: transparent;
        border-color: transparent;
        color: #a6a6a6
    }

    .nav-timeline-bar a:after{
        background-color: #514943;
        border: 4px solid #514943;
        border-radius: 100%;
        color: #ffffff;
        content: counter(i);
        counter-increment: i;
        height: 7px;
        left: 50%;
        line-height: 0.8;
        margin-left: -14px;
        position: absolute;
        right: auto;
        text-align: center;
        top: 7px;
        width: 7px;
        box-sizing: content-box;
    }

    .nav-timeline-bar a:before {
        background-color: #d6d6d6;
        border: 1px solid transparent;
        border-radius: 100%;
        content: '';
        height: 21px;
        left: 50%;
        line-height: 1;
        margin-left: -17px;
        margin-top: 4px;
        position: absolute;
        top: 0;
        width: 21px;
    }

    #warehouse_id::-ms-expand {
        display: none;
    }

    .coresuccess .content-header-floating a:before {color: #fff;}
    .coresuccess .content-header-floating .nav-timeline-bar:before{background-color: #009e8a;}
    .coresuccess .content-header-floating .nav-timeline-bar a:after {
        background-color: #009e8a;
        border: 4px solid #009e8a;
    }
    .coresuccess .content-header-floating .content-header table {
        float: left;
        background: none transparent;
        border-top: 1px solid transparent;
        border-bottom: 1px solid transparent;
        padding-left: 2px;
    }
    .coresuccess .content-header-floating .nav-timeline-bar:before {
        background-color: #d4d4d4;
        border-bottom: 1px solid #d9d9d9;
        border-top: 1px solid #bfbfbf;
        content: '';
        height: 9px;
        left: 38px;
        position: absolute;
        right: 50px;
        top: 11px;
    }
    .coresuccess .content-header-floating .nav-timeline-bar > li:after {
        background-color: #009e8a;
        content: '';
        height: 5px;
        left: -40px;
        position: absolute;
        top: 13px;
        width: 91%;
        box-sizing: inherit;
        right: 50px;
    }
    .coresuccess .content-header-floating .nav-timeline-bar > li.active ~ li a:after{background-color: #009e8a;border-color: #009e8a;    color: #fff;}
</style>