<div style="width: 100%;">
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head" style="margin-top: 10px">
                <h4 class="icon-head head-account"><?php echo $this->__('Bill Information') ?></h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Billed From: ') ?></label></td>
                        <td class="value a-right"><strong><?php echo $this->getBilledFrom() ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Bill Date: ') ?></label></td>
                        <td class="value a-right"><strong><?php echo $this->getBilledDate() ?></strong></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head" style="margin-top: 10px">
                <h4 class="icon-head head-account"><?php echo $this->__('Invoice Totals') ?></h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <tr>
                        <td class="label a-left">
                            <strong><label><?php echo $this->__('Grand Total (excl. Tax): ') ?></label></strong>
                        </td>
                        <td class="value a-right">
                            <strong><label><?php echo $this->getPriceFormat('grand_total_excl_tax'); ?></label></strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Discount: ') ?></label></td>
                        <td class="value a-right"><span><?php echo $this->getPriceFormat('total_discount'); ?></span></td>
                    </tr>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Tax: ') ?></label></td>
                        <td class="value a-right"><span><?php echo $this->getPriceFormat('total_tax'); ?></span>
                        </td>
                    </tr>
                    </tbody>

                    <tfoot>
                    <tr>
                        <td class="label a-left">
                            <strong><label><?php echo $this->__('Grand Total (incl. Tax): ') ?></label></strong>
                        </td>
                        <td class="value a-right">
                            <strong><label><?php echo $this->getPriceFormat('grand_total_incl_tax'); ?></label></strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="label a-left">
                            <strong><label><?php echo $this->__('Total Due: ') ?></label></strong>
                        </td>
                        <td class="value a-right">
                            <strong><label><?php echo $this->getPriceFormat('total_due'); ?></label></strong>
                        </td>
                    </tr>
                    <?php $totalRefund = $this->getPrice('total_refund'); ?>
                    <?php if ($totalRefund > 0): ?>
                        <tr>
                            <td class="label a-left">
                                <label><strong><?php echo $this->__('Total Refund: ') ?></strong></label>
                            </td>
                            <td class="value a-right">
                                <strong><label><?php echo $this->getPriceFormat('total_refund'); ?></label></strong>
                            </td>
                        </tr>
                    <?php endif; ?>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>