<?php
$_giftCard = $this->getGiftCard();
$_store = $this->getStore();
$url_barcode = $this->getUrlBarcode();
$_template = $this->getTemplateParam();
$currency = $this->getCurrency();
$_textColor = $this->getTextColor();
$_styleColor = $this->getStyleColor();
$expire_day = $this->getExpireDay();
$notes = $this->getNotes();
$resizeImage = $this->getResizeImage();
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magestore/print_style.css') ?>"
      media="all"/>
<div id="giftcard-template-simple" class="gift-card">
    <div class="simple-top">
        <img class="image-temp form-group"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/simple/' . $_giftCard->getGiftcardTemplateImage() ?>"
             style="width:100%;"/>
        <div class="template-simple-content">
            <div class="simple-content-top form-group">
                <div
                    class="<?php if ($url_barcode != ''): ?>col-xs-4<?php else: ?>col-xs-6<?php endif; ?> simple-logo">
                    <img
                        src="<?php echo $_giftCard->getPrintLogo() ? $_giftCard->getPrintLogo() : $this->getSkinUrl('images/logo_print.png') ?>"/>
                </div>
                <div
                    class="<?php if ($url_barcode != ''): ?>col-xs-4 two-border<?php else: ?>col-xs-6 no-right<?php endif; ?>">
                    <div class="giftcard-value form-group text-center">
                        <div class="value-price"><span class="giftcard-style-color giftcard-price-change"
                                                       style="color: <?php echo $_textColor ?>;"><?php echo $currency->format($_giftCard->getBalance()); ?></span>
                        </div>
                    </div>
                    <div class="giftcard-number form-group text-center">
                            <span class="giftcard-style-color"
                                  style="font-weight: 600; color: <?php echo $_styleColor ?>;"><?php echo $_giftCard->getGiftCode() ?></span>
                    </div>

                </div>
                <?php if ($url_barcode != ''): ?>
                    <div class="col-xs-4 simple-barcode text-center">

                        <img src="<?php echo $url_barcode ?>"/>

                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?php if ($_giftCard->getMessage()): ?>
        <div class="giftcard-message simple-bottom">
            <div class="giftcard-text-color giftcard-custom-message"
                 style="color: <?php echo $_textColor ?>;"><?php echo $_giftCard->getMessage() ?></div>
        </div>
    <?php endif; ?>
</div>
<footer></footer>