<tr>
    <td class="label">
        <label>
            <span><?php echo __('Installation guide')?></span>
        </label>
    </td>
    <td class="value vantiv-installation-guide">
        <h4 class="title"><?php echo __('Get your vantiv infomation')?></h4>
        <ul class="vantiv-installation-app-guide">
            <li>
                <ol class="guide-content">
                    <li>
                        <?php echo __('Email to')?>
                        <a href="mailto:certification@vantiv.com"><?php echo __("certification@vantiv.com")?></a>
                    </li>
                    <li>
                        <?php echo __('Or Create a developer account ');?>
                        <a href="http://www.elementps.com/Create-a-Test-Account"><?php echo __("Vantiv Developer")?></a>
                    </li>
                    <li><?php echo __('Check your email to get account information');?></li>
                    <li><?php echo __('Fill in Account ID, Application ID, Acceptor ID and Account Token');?></li>
                    <li><?php echo __('Refresh magento cache');?></li>
                </ol>
            </li>
        </ul>
    </td>
    <td class=""></td>
</tr>
<script>
    require([
        'jquery'
    ], function ($) {
        var testAPIUrl = '<?php echo $block->getTestApiUrl();?>';
        $(document).ready(function(){
            $('#webpos-vantiv-integration-test-api').click(function(){
                $("#webpos-vantiv-integration-test-response .loader").removeClass('hide');
                $.ajax({
                    method:'get',
                    url: testAPIUrl
                }).complete(function( result, status) {
                    $("#webpos-vantiv-integration-test-response .loader").addClass('hide');
                    if(status == 'success'){
                        var response = JSON.parse(result.responseText);
                        if(response && response.success){
                            $("#webpos-vantiv-integration-test-response .success").removeClass('hide');
                            $("#webpos-vantiv-integration-test-response .error").addClass('hide');
                        }else{
                            if(response && response.message){
                                alert(response.message);
                            }
                            $("#webpos-vantiv-integration-test-response .success").addClass('hide');
                            $("#webpos-vantiv-integration-test-response .error").removeClass('hide');
                        }
                    }else{
                        alert('<?php echo __('Please check your network connection');?>');
                    }
                });
            });
        });
    });
</script>
<style type="text/css">
    .hide{
        display: none;
    }
    .vantiv-installation-guide h4.title{
        padding-top:7px;
        padding-left:0px;
        margin-top:0px;
        margin-left:0px;
        font-size: 14px;
        font-weight: 600;
    }
    .vantiv-installation-guide ul li{
        list-style: none;
        margin: 5px 0px;
    }
    .vantiv-installation-guide ol li{
        list-style: inherit;
    }
    .vantiv-installation-guide li .guide-content{
        padding-left: 20px;
    }
    .loader {
        border: 6px solid #f3f3f3; /* Light grey */
        border-top: 6px solid #3498db; /* Blue */
        border-radius: 50%;
        width: 40px;
        height: 40px;
        animation: spin 1.5s linear infinite;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>