<div style="width: 100%;">
<!--    <div class="box-left">-->
        <?php if ($this->getReturnReason()): ?>
<!--            <div class="entry-edit">-->
<!--                <div class="fieldset">-->
<!--                    <div class="entry-edit-head" style="margin-top: 10px">-->
<!--                        <h4 class="icon-head head-account">--><?php //echo $this->__('Reason: ') ?><!--</h4>-->
<!--                    </div>-->
<!--                    <div style="padding-top: 5px;">--><?php //echo $this->getReturnReason(); ?><!--</div>-->
<!--                </div>-->
<!--            </div>-->
        <?php endif; ?>
<!--    </div>-->
</div>