<?php
/**
 * @var Magestore_Purchaseordersuccess_Block_Adminhtml_Purchaseorder_Edit_Tab_Returneditem_Scan $this
 */
?>
<div class="modal right fade" id="scan-barcode-return-item-modal" tabindex="-1" role="dialog"
     aria-labelledby="modalLabel">
    <div class="modal-dialog" role="document" id="scan_barcode_returned_item_modal_dialog">
        <div class="modal-content">
            <h2 class="modal-title" data-role="title"><?php echo $this->__("Scan Barcode") ?></h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <div class="modal-header">
                <button id="submit-barcode-return-item" class="action-primary import_button" type="button" data-role="action"
                        data-dismiss="modal">
                    <span><?php echo $this->__('Save') ?></span>
                </button>
            </div>
            <div class="modal-body">
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-edit-form fieldset-legend">
                            <?php echo $this->__('Scan Barcode'); ?>
                        </h4>
                    </div>
                    <div class="purchaseorder_fieldset fieldset">
                        <?php echo $this->addScanBarcodeField(); ?>
                    </div>
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-edit-form fieldset-legend">
                            <?php echo $this->__('Scan Item List'); ?>
                        </h4>
                    </div>
                    <table class="actions"></table>
                    <div class="grid">
                        <table class="data" id="barcode-table-return-item">
                            <colgroup>
                                <col width="55">
                                <col>
                                <col>
                                <col>
                                <col width="150">
                            </colgroup>
                            <thead>
                            <tr class="headings">
                                <th class="a-center"><?php echo $this->__("Barcode") ?></th>
                                <th class="a-center"><?php echo $this->__("QTY") ?></th>
                                <th class="a-center"><?php echo $this->__("SKU") ?></th>
                                <th class="a-center"><?php echo $this->__("Supplier SKU") ?></th>
                                <th class="a-center"><?php echo $this->__("Product Name") ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var scanBarcodeReturnItemObject = new PurchaseorderSuccessJS({
        "parentGridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $this->getJsParentObjectName() . '"' ?: '{}'; ?>,
        "saveUrl": <?php /* @escapeNotVerified */ echo '"' . $this->getSubmitBarcodeUrl() . '"' ?: '""'; ?>,
        "tabContainer": <?php /* @escapeNotVerified */ echo '"' . $this->getTabContainer() . '"'; ?>,
        "tabsReload": <?php /* @escapeNotVerified */ echo $this->getReloadTabs(); ?>
    });

    var scanBarcodeReturnItem = new ScanBarcode({
        'table': 'barcode-table-return-item',
        'input': 'barcode-return-item',
        'loadBarcodeUrl': '<?php echo $this->getLoadBarcodeUrl(); ?>',
    });

    scanBarcodeReturnItem.submit = function (params) {
        params.returned_at = $('scan_barcode_returned_at').value;
        scanBarcodeReturnItemObject.save(null, params);
    };

    Event.observe($('submit-barcode-return-item'), 'click', function (event) {
        if (!new Validation('scan-barcode-return-item-modal').validate()) {
            return event.stopPropagation();
        }
        if (Object.keys(scanBarcodeReturnItem.getEditedBarcodes()).length <= 0) {
            alert('<?php echo $this->__('Please return at least one item.') ?>')
            return event.stopPropagation();
        }
        scanBarcodeReturnItem.submitBarcode();
    });
</script>

