<?php
/**
 * Magestore
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magestore.com license that is
 * available through the world-wide-web at this URL:
 * http://www.magestore.com/license-agreement.html
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Magestore
 * @package     Magestore_Inventorysuccess
 * @copyright   Copyright (c) 2016 Magestore (http://www.magestore.com/)
 * @license     http://www.magestore.com/license-agreement.html
 */

/**
 * Adjuststock Model
 * 
 * @category    Magestore
 * @package     Magestore_Inventorysuccess
 * @author      Magestore Developer
 */
class Magestore_Inventorysuccess_Model_LowStockNotification_Rule_Product extends Mage_Core_Model_Abstract
{
    /**#@+
     * Rule product's fields
     */
    const RULE_PRODUCT_ID = 'rule_product_id';
    const RULE_ID = 'rule_id';
    const PRODUCT_ID = 'product_id';

    public function _construct()
    {
        parent::_construct();
        $this->_init('inventorysuccess/lowStockNotification_rule_product');
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    /**
     * @param mixed $id
     * @return Mage_Core_Model_Abstract
     */
    public function setId($id)
    {
        return parent::setId($id); // TODO: Change the autogenerated stub
    }

    /**
     * Get rule id
     *
     * @return int
     */
    public function getRuleId()
    {
        return $this->_getData(self::RULE_ID);
    }

    /**
     * Set rule id
     *
     * @param int $ruleId
     * @return $this
     */
    public function setRuleId($ruleId)
    {
        return $this->setData(self::RULE_ID, $ruleId);
    }

    /**
     * Get product id
     *
     * @return int
     */
    public function getProductId()
    {
        return $this->_getData(self::PRODUCT_ID);
    }

    /**
     * Set product id
     *
     * @param int $productId
     * @return $this
     */
    public function setProductId($productId)
    {
        return $this->setData(self::PRODUCT_ID, $productId);
    }
}