<?php
    $userGuide =  Mage::helper('storepickup')->__('
	Store Pickup extension is used as a Magento shipping method. Follow these steps to configure the module:<br />
        1. To add/ import stores with location, time schedule and other information, go to <strong>Store Pickup</strong> -> <strong>Manage Stores</strong><br />
        2. To set days off for store(s), go to <strong>Store Pickup</strong> -> <strong>Manage Holidays</strong><br />
        3. To set days with special working time for store(s), go to <strong>Store Pickup</strong> -> <strong>Manage Special Days</strong><br />
        4. To configure Store Pickup extension, go to <strong>Systems</strong> -> <strong>Configuration</strong> -> <strong>Shipping Methods</strong> -> <strong>Store Pickup</strong><br />
    ');
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('storepickup')->__('General Instructions') ?></h4>        
    </div>
    <div class="fieldset ">
        <div class="hor-scroll">
            <?php echo $userGuide ?>
        </div>
    </div>
    
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('storepickup')->__('Instructions to create Google Map API Key') ?></h4>        
    </div>
    <div class="fieldset ">
        <div class="hor-scroll" >
            <?php echo '<strong><u>Step 1:</u></strong>  Visit the APIs Console at'?> <a href="https://console.developers.google.com/apis/library" target="_blank"><?php echo 'https://console.developers.google.com/apis/library' ?></a><?php echo ' and log in with your Google Account.' ?>
            <br />
            <?php echo 'Then, Click on the <strong>Create project</strong> tab in the top menu.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/google-create-project.png' ?>" title="<?php echo __('Google API Active') ?>" />
            <br />
            <?php echo '<strong><u>Step 2:</u></strong> Fill project name and click Create button' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/fill-name.png' ?>" title="<?php echo __('Google API Active') ?>" />
            <br />
            <br />
            <?php echo '<strong><u>Step 3:</u></strong> On the menu at the left side, you will see the  <strong>Credentials</strong>. Click this tab and after that, a box will appear with <strong>"API key"</strong>  on it. It is where you should click in order to create API key for your browser apps.' ?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/choose-api.png' ?>" title="<?php echo __('Google API Active') ?>" />
            <br />
            <br />
            <?php echo "After that you will see a box with a number of choices specifying which kind of key you would like to create. Choose  <strong>Browser key</strong> "?>
            <br />
            <br />
            <img src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/choose-browser.png' ?>" title="<?php echo __('Google API Active') ?>" />
            <br />
            <br />
            <?php echo "<strong><u>Step 4:</u></strong> Fill in your name and domain and then click create"?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/fill-domain.png' ?>" title="<?php echo __('Google API Active') ?>" />
            <br />
            <br />
            <?php echo "<strong><u>Step 5:</u></strong> Get the key and paste it in your page. "?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/get-key.png' ?>" title="<?php echo __('Google API Active') ?>" />
            <br />
            <?php echo "<strong><u>Step 6:</u></strong>  Last but not least,in <strong>Library</strong> tab, let’s enable the APIs in red frame as below "?>
            <br />
            <br />
            <img width="80%" src="<?php echo Mage::getBaseUrl('media').'storepickup/guide/enable-apis1.png' ?>" title="<?php echo __('Google API Active') ?>" />
            <br />
        </div>
    </div>

</div>