<script type="text/javascript">
    var PrintForm = function (data) {
        for (var item in data) {
            PrintForm.prototype[item] = data[item];
        }
    };
    PrintForm.prototype = {
        loadPreview: function () {
            var params = {
                templateId: this.getTemplateId()
            };
            var self = this;
            new Ajax.Request(this.loadPreviewUrl, {
                method: 'post',
                parameters: params,
                onComplete: function (response) {
                    var data = response.responseJSON;
                    self.previewContent(data.content);
                }
            });
        },
        print: function () {
            var params = {
                barcodes: this.getBarcodes(),
                templateId: this.getTemplateId()
            };
            var self = this;
            if (editForm.validate()) {
                new Ajax.Request(this.printConfigUrl, {
                    method: 'post',
                    parameters: params,
                    onComplete: function (response) {
                        var data = response.responseJSON;
                        if (data.content) {
                            var print_window = window.open('', 'print', 'status=1,width=700,height=700');
                            if (print_window) {
                                print_window.document.open();
                                print_window.document.write(data.content);
                                print_window.document.close();
                                print_window.addEventListener('load', function () {
                                    print_window.print();
                                });
                            } else {
                                alert('Your browser has blocked the automatic popup, please change your browser settings or print the receipt manually');
                            }
                        }
                    }
                });
            }
        },
        getBarcodes: function () {
            return $$('input[name=barcodes]')[0].value;
        },
        getTemplateId: function () {
            return $('template_id').value;
        },
        getBarcodePreviewElement: function () {
            return $$('.barcode_preview_container')[0];
        },
        previewContent: function (content) {
            if (typeof content == 'undefined') {
                return this.getBarcodePreviewElement().innerHTML;
            } else {
                this.getBarcodePreviewElement().innerHTML = content;
            }
        }

    };
    window.printForm = new PrintForm({
        'loadPreviewUrl': '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/barcodesuccess_barcode/loadPrintPreview') ?>',
        'printConfigUrl': '<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/barcodesuccess_barcode_print/printConfig') ?>'
    });
    window.printForm.loadPreview();
</script>
