<?php
/**
 * Created by Wazza Rooney on 7/21/17 10:33 AM
 * Copyright (c) 2017. All rights reserved.
 * Last modified 7/21/17 10:33 AM
 */

class Magestore_Webpos_Block_Head extends Mage_Page_Block_Html_Head
{
    public function getCssJsHtml()
    {
        return parent::getCssJsHtml(); // TODO: Change the autogenerated stub
    }

    public function getChildChildHtml($name, $childName = '', $useCache = true, $sorted = false)
    {
//        return parent::getChildChildHtml($name, $childName, $useCache, $sorted); // TODO: Change the autogenerated stub
    }

    public function getIncludes()
    {
//        return parent::getIncludes(); // TODO: Change the autogenerated stub
    }
}