<div class="ms-webpos" data-bind="scope: 'warning'">
    <div class="login-screen">
        <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" style="display: block">
            <div class="loader">
                <!--
            <img src="<?php /* @escapeNotVerified */
                echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */
                echo __('Loading...'); ?>"
                 style="position: absolute;">
            -->
            </div>
        </div>
        <div class="wrap-warning-form" style="width: 80%;margin-left: 10%;left:0;">
            <div data-bind="">
                <h1 class="title-page"><img src="<?php echo $block->getWarningLogoUrl(); ?>" width="200px" height="200px"
                                            alt="logo"/></h1>
                <div class="warning-message">
                    <p>
                        <?php echo __('System has detected that your account is being used on another device.'); ?>
                    </p>
                    <p>
                        <?php echo __('Do you want to log out of that device and stay on the current one?'); ?>
                    </p>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-default"
                            data-bind="click: accept"><?php echo __('Continue to sign in'); ?></button>
                    <button type="button" class="btn btn-cancel"
                            data-bind="click: cancel"><?php echo __('Cancel'); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
            {
                ".ms-webpos": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
    echo $block->getJsLayout(); ?>
                 }
             }

</script>
<script>
    var WEBPOS = {};
    //var ObjectManager = {};
    <?php
    $config = $block->getWebposConfig();
    ?>
    window.webposConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($config); ?>;
    window.posConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getPosList()); ?>;
    window.locationConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getLocationList()); ?>;
</script>

<script>
    require([
        'mage/url',
        'Magento_Ui/js/block-loader'
    ], function(url, blockLoader) {
        blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
        return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
    });

    require([
        'Magestore_Webpos/js/model/webpos',
    ], function (webposModel) {
        WEBPOS = webposModel();
        WEBPOS.setConfig(window.webposConfig);
    });
</script>