<?php
$_giftCard = $this->getGiftCard();
$_store = $this->getStore();
$url_barcode = $this->getUrlBarcode();
$_template = $this->getTemplateParam();
$currency = $this->getCurrency();
$_textColor = $this->getTextColor();
$_styleColor = $this->getStyleColor();
$expire_day = $this->getExpireDay();
$notes = $this->getNotes();
$resizeImage = $this->getResizeImage();
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magestore/print_style.css') ?>"
      media="all"/>
<div id="giftcard-template-left giftcard-print" style="float:left; width: 600px;">
    <div class="giftcard-template-content-left giftcard-change-image" style="">
        <img class="image-temp"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/left/' . $_giftCard->getGiftcardTemplateImage() ?>"
             width="250" height="365" style=""/>
        <?php if ($_giftCard->getPrintLogo()): ?>
            <div class="bkg-logo" style="">
                <img src="<?php echo $_giftCard->getPrintLogo() ?>" width="auto" height="63"
                     style="max-width: 175px"/>
            </div>
        <?php endif; ?>
        <div class="expire-day expire-day-top"
             style="font-size: 11px; margin-top: -25px;  text-align: center; color: white; font-weight: bold;"><?php if (Mage::helper('giftvoucher')->getGeneralConfig('show_expiry_date') && $_giftCard->getExpiredAt()) echo $this->__('Expired: ') . $expire_day ?></div>
    </div>
    <div class="giftcard-template-content">
        <img class="image-temp"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/left/' . $_template->getBackgroundImg() ?>"
             width="350" height="365"/>
        <div style="float: left;position: absolute;width: 350px;top: 0;">
            <div class="giftcard-mag">
                <div class="giftcard-style-color giftcard-title" style="color: <?php echo $_styleColor ?>">
                    <?php echo $_template->getCaption() ?>
                </div>
                <div style="margin: 0px 5px 0px 5px;">
                    <div class="giftcard-from-to" style="float: left">
                            <span class="giftcard-from" style="float: left;margin-bottom: 5px; ">
                                <label class="giftcard-text-color"
                                       style="float: left;margin-right: 5px;font-weight: 600;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('From:') ?></label>
                                <span class="giftcard-text-color giftcard-send-from print-font"
                                      style="font-size: 16px;margin-top: 0px;color: <?php echo $_styleColor ?>"><?php echo $_giftCard->getCustomerName() ?></span>
                            </span>
                            <span class="giftcard-to" style="float: left;clear: both;">
                                <label class="giftcard-text-color" for="giftcard-to"
                                       style="float: left;font-weight: 600;color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('To:') ?> </label>
                                <span class="giftcard-text-color giftcard-send-to print-font"
                                      style="margin-left: 5px;font-size: 16px;color: <?php echo $_styleColor ?>"><?php echo $_giftCard->getRecipientName() ?></span>
                            </span>
                    </div>
                    <div class="message-box">
                        <div class="giftcard-text-box">
                            <p class=""
                               style="padding: 0 10px;font-size: 12px; color: <?php echo $_textColor ?>;"><?php echo $_giftCard->getMessage() ?></p>
                        </div>
                    </div>
                    <div style="float: left; width: 100%;  margin-top: 10px; ">
                        <div style="float: left;">
                                <span class="print-font giftcard-text-color"
                                      style="color: <?php echo $_textColor ?>"><?php echo Mage::helper('giftvoucher')->__('Value') ?></span>
                                <span class="giftcard-style-color giftcard-price-change"
                                      style="float: left; clear: both; font-size: 26px; color: <?php echo $_styleColor ?>; font-weight: bold"><?php echo $currency->format($_giftCard->getBalance()); ?></span>
                        </div>
                        <div class="barcode-giftcard" style="float: right;width: 170px;text-align: right;">
                            <?php if ($url_barcode != ''): ?>
                                <span
                                    style=" margin-bottom: 5px; font-style: italic; width: 133%;float: right;font-weight: 600; color: <?php echo $_styleColor ?>;"><?php echo $_giftCard->getGiftCode() ?></span>
                                <span style="width: 180px;float: right;">
                                        <img
                                            src="<?php echo $url_barcode ?>" <?php if ($resizeImage) echo 'width="180" height="40"' ?>
                                            height="40" style="float: right;"/>
                                    </span>
                            <?php else: ?>
                                <span
                                    style=" margin-bottom: 5px; font-style: italic; width: 142%;float: right;font-weight: 600; color: <?php echo $_styleColor ?>;"><?php echo $_giftCard->getGiftCode() ?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="giftcard-text" style="float: left;width: 100%;">
                        <p class="print-font giftcard-text-color "
                           style="font-size: 12px;height: 55px;overflow: hidden;color: <?php echo $_textColor ?>"><?php echo $notes ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer></footer>