<?php

/* 
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="modal right fade" id="<?php echo $this->getModalId() ?>" tabindex="-1" role="dialog"
     aria-labelledby="modalLabel" style="display:none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <h2 class="modal-title" data-role="title"><?php echo $this->__($this->getTitle()) ?></h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <div class="modal-header">
                <button id="submit-import" class="action-primary import-csv" type="button"
                        onclick="submitImportForm('<?php echo $this->getModalId() ?>-form');">
                    <span><span><span><?php echo $this->__('Import') ?></span></span></span>
                </button>
            </div>
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Instruction') ?></h4>
                </div>
                <div class="fieldset">
                    <ul class="content">
                        <li class="item">
                            <span><?php echo $this->__($this->getContent()); ?></span>
                            <div class="clear"></div>
                        </li>
                        <li class="item">
                            <span><a
                                    href="<?php echo $this->getCsvSampleLink(); ?>"><?php echo $this->__('Download sample file'); ?></a></span>
                        </li>
                    </ul>
                    <div class="import-product hor-scroll">
                        <form id="<?php echo $this->getModalId() ?>-form" action="<?php echo $this->getImportLink() ?>"
                              method="post" enctype="multipart/form-data">
                            <?php echo $this->getBlockHtml('formkey') ?>
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                <tr>
                                    <td class="label">
                                        <label
                                            for="import_file_input"><?php echo $this->__('Please choose  a CSV file to import') ?></label>
                                    </td>
                                    <td class="value">
                                        <input id="import_file_input" name="import_product"
                                               class="required-entry input-file" type="file"
                                               onchange="fileSelected(this);">
                                        <div id="import_file_input_description"></div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- modal-content -->
    </div><!-- modal-dialog -->
</div><!-- modal -->

<script type="text/javascript">

    function submitImportForm(formId) {
        var form = new varienForm(formId);
        if (form.validate()) {
            form.submit();
        }
    }

    function fileSelected(element) {
        var file = element.files[0];
        if (file) {
            var allowedTypes = <?php echo $this->getAllowedFileTypes() ?>;
            var fileIsAllowed = false;
            for (var i in allowedTypes) {
                if (file.type === allowedTypes[i]) {
                    fileIsAllowed = true;
                }
            }
            if (!fileIsAllowed) {
                //alert('<?php echo $this->getData('invalid_file_message')?>');
            }
            var fileSize = 0;
            if (file.size > 1024 * 1024) {
                fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
            } else {
                fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';
            }
            var fileDesciption = '';
            fileDesciption += '<?php echo $this->__('Name')?>' + ': ' + file.name + '<br/>';
            fileDesciption += '<?php echo $this->__('Size')?>' + ': ' + fileSize + '<br/>';
            //fileDesciption += '<?php echo $this->__('Type')?>' + ': ' + file.type;
            $('import_file_input_description').innerHTML = fileDesciption;
        }
    }
</script>