<div style="width: 100%;">
    <div class="box-left">
        <?php if ($this->getPurchaseOrderComment()): ?>
            <div class="entry-edit">
                <div class="fieldset">
                    <div class="entry-edit-head" style="margin-top: 10px">
                        <h4 class="icon-head head-account"><?php echo $this->__('Comment') ?></h4>
                    </div>
                    <div style="padding-top: 5px;"><?php echo $this->getPurchaseOrderComment(); ?></div>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head" style="margin-top: 10px">
                <h4 class="icon-head head-account"><?php echo $this->__('Order Totals') ?></h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Subtotal: ') ?></label></td>
                        <td class="value a-right"><span><?php echo $this->getPriceFormat('subtotal'); ?></span></td>
                    </tr>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Shipping Cost: ') ?></label></td>
                        <td class="value a-right"><span><?php echo $this->getPriceFormat('shipping_cost'); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Discount: ') ?></label></td>
                        <td class="value a-right"><span><?php echo $this->getPriceFormat('total_discount'); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="label a-left"><label><?php echo $this->__('Tax: ') ?></label></td>
                        <td class="value a-right"><span><?php echo $this->getPriceFormat('total_tax'); ?></span></td>
                    </tr>
                    </tbody>

                    <tfoot>
                    <tr>
                        <td class="label a-left">
                            <strong><label><?php echo $this->__('Grand Total (excl. Tax): ') ?></label></strong>
                        </td>
                        <td class="value a-right">
                            <strong><label><?php echo $this->getPriceFormat('grand_total_excl_tax'); ?></label></strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="label a-left">
                            <strong><label><?php echo $this->__('Grand Total (incl. Tax): ') ?></label></strong>
                        </td>
                        <td class="value a-right">
                            <strong><label><?php echo $this->getPriceFormat('grand_total_incl_tax'); ?></label></strong>
                        </td>
                    </tr>
                    <?php $totalBilled = $this->getPrice('total_billed'); ?>
                    <?php $totalDue = $this->getPrice('total_due'); ?>
                    <?php if ($totalBilled > 0): ?>
                        <tr>
                            <td class="label a-left">
                                <label><strong><?php echo $this->__('Total Bill: ') ?></strong></label>
                            </td>
                            <td class="value a-right">
                                <strong><label><?php echo $this->getPriceFormat('total_billed'); ?></label></strong>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($totalDue > 0): ?>
                    <tr>
                        <td class="label a-left">
                            <strong><label><?php echo $this->__('Total Due: ') ?></label></strong>
                        </td>
                        <td class="value a-right">
                            <strong><label><?php echo $this->getPriceFormat('total_due'); ?></label></strong>
                        </td>
                    </tr>
                    <?php endif; ?>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>