<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

echo __('Please select a warehouse to view stock'); ?></br></br>
<?php echo __('Warehouse'); ?>&nbsp
<select id="select_warehouse_option">
    <option value="0"><?php echo __('All Warehouses'); ?></option>
    <?php foreach ($block->getOptionWarehouses() as $warehouse): ?>
        <option value="<?php echo $warehouse->getWarehouseId() ?>"><?php echo $warehouse->getWarehouse() ?></option>
    <?php endforeach; ?>
</select>
