<html><head><style>
        #giftcard-template-back p, #giftcard-template-back span,
        p, span, label{
            font-family: 'Open Sans', sans-serif;
        }
        .giftcard-print-top p, .giftcard-print-top span, print-font{
            font-family: 'Open Sans', sans-serif;
        }
        .print-notes{
            color: orange;
            text-decoration: none;
            font-family: 'Open Sans', sans-serif;
            font-weight: 600;
            font-size: 12px;
        }
        .giftcard-text-color{
            font-size: 16px;
            font-weight: 600;
        }
        #giftcard-template-back a,
        .giftcard-print-top a{font-size: 12px;}
        .print-font{
            font-size: 12px;
            float: left;
            font-weight: 600;
            font-family: 'Open Sans', sans-serif;
        }
        .giftcard-template-content-left.giftcard-change-image{
            float: left;
            width: 250px;
        }

        .bkg-logo{
            float: left;
            position: absolute;
            top: 287px;
            text-align: center;
            width: 250px;
        }
        .giftcard-print{
            float: left;
            width: 600px;
        }
        .giftcard-template-content img {
            float: left !important;
        }
        .giftcard-template-content{
            float: left !important;
             position: absolute;
            width: 350px;
            height: 365px;
        }
        .giftcard-mag{
            margin: 15px 10px;
        }
        .giftcard-style-color.giftcard-title{
            font-size: 20px;
            font-weight: 600;
            margin-bottom: 5px;
            font-family: 'Open Sans', sans-serif;
        }
        .message-box {
            height: 97px;
            background: #fff;
            border: 1px solid #ececec;
            border-radius: 5px;
            float: left;
            width: 100%;
            margin-top: 6px;
        }
        .message-box-top{
            width: 342px;
            height: 97px;
            display: table-cell;
            vertical-align: middle;
            color: #0A2F23;
            background: #fff;
            border: 1px solid #ececec;
            border-radius: 5px;
            clear: both;
            float: left;
        }

        #giftcard-template-simple{
            width:600px;
            margin:0 auto 20px;
            float:left;
            border: 1px solid #ddd;
            border-radius: 3px;
        }
        #giftcard-template-simple .simple-top {
            padding: 6px;
            float: left;
            width: 100%;
        }
        .simple-bottom {
            float: left;
            width: 100%;
            padding: 10px;
            border-top: 1px solid #ddd;
            height: 90px;
            overflow: hidden;
        }
        #giftcard-template-simple  img{margin:auto;
            max-width: 100%;}
        .simple-content-top .simple-logo img{max-height: 90px;max-width:100%;}
        #giftcard-template-simple .simple-content-top .col-xs-4,#giftcard-template-simple .simple-content-top .col-xs-6{
            height:90px;
        }
        .simple-content-top .simple-logo{

            min-height: 85px;
            display:flex;
        }
        .gift-card .form-group {
            margin-bottom: 5px;
            margin-top:10px;
            float: left;
            width: 100%;
            text-align: left;
        }
        .gift-card .text-center {
            text-align: center;
        }
        .gift-card * {
            box-sizing: border-box;
        }
        .gift-card .col-xs-4,.gift-card .col-xs-6{
            float:left;
            padding-right: 10px;
            padding-left: 10px;
            position: relative;
            min-height: 85px;
        }
        .gift-card .col-xs-4{    width: 33.33333333%;}
        .gift-card .col-xs-4 img{max-width: 180px; max-height: 90px;}
        .gift-card .col-xs-6{width: 50%;}
        .simple-bottom .giftcard-custom-message {
            width: 100%;
            float: left;
            margin: 0;
            font-size: 14px;
            color: #444;
            line-height: 18px;
            max-height: 70px;
            overflow: hidden;
        }
        .simple-barcode img{
            height: 35px;
            margin:auto;
        }
        #giftcard-template-simple .simple-barcode{
            min-height: 85px;
            display:flex;
        }
        .template-simple-content .giftcard-price-change{font-size: 30px;}
        .template-simple-content .giftcard-number .giftcard-style-color{font-size: 15px;}
        .two-border{
            border-left:1px solid #ddd;
            border-right: 1px solid #dddddd;
        }
        .no-right{border-left:1px solid #ddd;}
        #giftcard-template-simple .giftcard-number .giftcard-style-color{ font-style: normal;}
    </style>
</head><body><div id="giftcard-template-left giftcard-print" style="float:left; width: 600px;">
    <div class="giftcard-template-content-left giftcard-change-image" style="">
        <img class="image-temp" src="http://magento.mage2tuts.com/media/giftvoucher/template/images/left/default.png" width="250" height="365" style="">
        <div class="expire-day expire-day-top" style="font-size: 11px; margin-top: -25px;  text-align: center; color: white; font-weight: bold;"></div>
    </div>
    <div class="giftcard-template-content">
        <img class="image-temp" src="http://magento.mage2tuts.com/media/giftvoucher/template/background/left/default.png" width="350" height="365">
        <div style="float: left;position: absolute;width: 350px;top: 0;">
            <div class="giftcard-mag">
                <div class="giftcard-style-color giftcard-title" style="color: orange">
                </div>
                <div style="margin: 0px 5px 0px 5px;">
                    <div class="giftcard-from-to" style="float: left">
                            <span class="giftcard-from" style="float: left;margin-bottom: 5px; ">
                                <label class="giftcard-text-color" style="float: left;margin-right: 5px;font-weight: 600;color: #2f2f2f">From:</label>
                                <span class="giftcard-text-color giftcard-send-from print-font" style="font-size: 16px;margin-top: 0px;color: orange"></span>
                            </span>
                            <span class="giftcard-to" style="float: left;clear: both;">
                                <label class="giftcard-text-color" for="giftcard-to" style="float: left;font-weight: 600;color: #2f2f2f">To: </label>
                                <span class="giftcard-text-color giftcard-send-to print-font" style="margin-left: 5px;font-size: 16px;color: orange"></span>
                            </span>
                    </div>
                    <div class="message-box">
                        <div class="giftcard-text-box">
                            <p class="" style="padding: 0 10px;font-size: 12px; color: #2f2f2f;"></p>
                        </div>
                    </div>
                    <div style="float: left; width: 100%;  margin-top: 10px; ">
                        <div style="float: left;">
                            <span class="print-font giftcard-text-color" style="color: #2f2f2f">Value</span>
                            <span class="giftcard-style-color giftcard-price-change" style="float: left; clear: both; font-size: 26px; color: orange; font-weight: bold"><span class="price">$0.00</span></span>
                        </div>
                        <div class="barcode-giftcard" style="float: right;width: 170px;text-align: right;">
                            <span style=" margin-bottom: 5px; font-style: italic; width: 133%;float: right;font-weight: 600; color: orange;">GIFT-KLXU-5555555</span>
                                    <span style="width: 180px;float: right;">
                                        <img src="http://magento.mage2tuts.com/media/giftvoucher/template/barcode/GIFT-KLXU-5555555.png" width="180" height="40" style="float: right;">
                                    </span>
                        </div>
                    </div>
                    <div class="giftcard-text" style="float: left;width: 100%;">
                        <p class="print-font giftcard-text-color " style="font-size: 12px;height: 55px;overflow: hidden;color: #2f2f2f">Converting to cash is not allowed. You can use the gift card code or redeem it to pay for your order at <span class="print-notes">http://magento.mage2tuts.com/index.php/</span>.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body></html>