<script type="text/javascript">
    function paypalLogin(){
        var redirectUrl = '<?php echo $this->getRedirectUrl()?>';
        var clientId = '<?php echo $this->getClientId()?>';
        var loginUrl = '<?php echo $this->getPaypalLoginUrl()?>';
        var url = loginUrl+'?scope=openid https://uri.paypal.com/services/paypalattributes/business https://uri.paypal.com/services/paypalhere address email&response_type=code&redirect_uri='+redirectUrl+'&client_id='+clientId;
        var signin_window = window.open(url, 'paypal_login', 'status=1,width=500,height=700');
        if(signin_window){
            signin_window.open();
        }else{
            alert("<?php echo $this->__('Your browser has blocked the automatic popup, please change your browser setting or print the receipt manually');?>");
        }
    }
</script>

<?php echo $this->getButtonHtml() ?>